{"name": "Test Failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "@allure.epic(\"EPIC_1\")\n    @allure.parent_suite('Parent Suite 1')\n    @allure.feature(\"Calculator Tests\")\n    @allure.title(\"Test Failure\")\n    def test_failure():\n        print(\"TC failure here\")\n>       assert 3 == 4\nE       assert 3 == 4\n\ntest_calculator.py:70: AssertionError"}, "attachments": [{"name": "stdout", "source": "bf26b650-8a2e-49a9-840d-110330c1567e-attachment.txt", "type": "text/plain"}], "start": 1692911106709, "stop": 1692911106709, "uuid": "39177b62-716e-44d2-bc3a-9286d7af6448", "historyId": "2b9180ad6a4e73145c7220e56ef622f9", "testCaseId": "2b9180ad6a4e73145c7220e56ef622f9", "fullName": "test_calculator#test_failure", "labels": [{"name": "parentSuite", "value": "Parent Suite 1"}, {"name": "epic", "value": "EPIC_1"}, {"name": "feature", "value": "Calculator Tests"}, {"name": "suite", "value": "test_calculator"}, {"name": "host", "value": "fv-az449-557"}, {"name": "thread", "value": "2047-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}